//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <string.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct vtable_8048848_type {
    int32_t (*e0)(int32_t *, int32_t *);
    int32_t (*e1)(int32_t *, int32_t *);
};

// ------------------------- Classes --------------------------

// N

// ------------------- Function Prototypes --------------------

int32_t _ZN1N13setAnnotationEPc(int32_t * result, char * str);
int32_t _ZN1NC1Ei(int32_t * result, int32_t a2);
int32_t _ZN1NmiERS_(int32_t * result, int32_t * a2);
int32_t _ZN1NplERS_(int32_t * result, int32_t * a2);

// --------------------- Global Variables ---------------------

struct vtable_8048848_type g1 = {
    .e0 = _ZN1NplERS_,
    .e1 = _ZN1NmiERS_
}; // 0x8048848

// ------- Dynamically Linked Functions Without Header --------

int32_t * _Znwj(int32_t a1);

// ------------------------ Functions -------------------------

// Address range: 0x80485f4 - 0x804869a
int main(int argc, char ** argv) {
    if (argc <= 1) {
        // 0x8048604
        _exit(1);
        // UNREACHABLE
    }
    int32_t * v1 = _Znwj(108); // 0x8048617
    _ZN1NC1Ei(v1, 5);
    int32_t * v2 = _Znwj(108); // 0x8048639
    _ZN1NC1Ei(v2, 6);
    _ZN1N13setAnnotationEPc(v1, (char *)*(int32_t *)((int32_t)argv + 4));
    return (int32_t)v2;
}

// Address range: 0x80486f6 - 0x804870d
// From class:    N
// Type:          constructor
// Demangled:     N::N(int)
int32_t _ZN1NC1Ei(int32_t * result, int32_t a2) {
    int32_t result2 = (int32_t)result;
    *result = (int32_t)&g1;
    *(int32_t *)(result2 + 104) = a2;
    return result2;
}

// Address range: 0x804870e - 0x804873a
// Demangled:     N::setAnnotation(char*)
int32_t _ZN1N13setAnnotationEPc(int32_t * result, char * str) {
    int32_t len = strlen(str); // 0x804871a
    return (int32_t)memcpy((int32_t *)((int32_t)result + 4), (int32_t *)str, len);
}

// Address range: 0x804873a - 0x804874d
// From class:    N
// Type:          virtual member function
// Demangled:     N::operator+(N&)
int32_t _ZN1NplERS_(int32_t * result, int32_t * a2) {
    int32_t v1 = *(int32_t *)((int32_t)a2 + 104); // 0x8048746
    return v1 + *(int32_t *)((int32_t)result + 104);
}

// Address range: 0x804874e - 0x8048765
// From class:    N
// Type:          virtual member function
// Demangled:     N::operator-(N&)
int32_t _ZN1NmiERS_(int32_t * result, int32_t * a2) {
    int32_t v1 = *(int32_t *)((int32_t)a2 + 104); // 0x804875a
    return *(int32_t *)((int32_t)result + 104) - v1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.6.3)
// Detected functions: 5

